<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260330" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixHide.Domain\PixHide.Domain.csproj" />
  </ItemGroup>

</Project>
