<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>PixHide.WinUI3App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>

	 <!--
	  Type 'OpenCvSharp.Mat' implements generic WinRT interfaces which requires generated code using unsafe for trimming and AOT compatibility if passed across the WinRT ABI.
	  Project needs to be updated with '<AllowUnsafeBlocks>true</AllowUnsafeBlocks>'.
	 -->
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

	<DefaultLanguage>en-US</DefaultLanguage>

	<AssemblyName>PixHide</AssemblyName>

	<LangVersion>14.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\PixHideIcon.ico" />
    <Content Remove="Assets\PixHideIcon.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" />
    <Content Remove="Assets\Square44x44Logo.scale-100.png" />
    <Content Remove="Assets\Square44x44Logo.scale-125.png" />
    <Content Remove="Assets\Square44x44Logo.scale-150.png" />
    <Content Remove="Assets\Square44x44Logo.scale-200.png" />
    <Content Remove="Assets\Square44x44Logo.scale-400.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-48.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\PixHideIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\PixHideIcon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.OpacityMaskView" Version="0.1.251217-build.2433" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.6" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1721" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageReference Include="NeoSmart.PrettySize" Version="3.1.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260330" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.6" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Square44x44Logo.scale-200.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Layouts\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PixHide.Infrastructure\PixHide.Infrastructure.csproj" />
    <ProjectReference Include="..\PixHide.Application\PixHide.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\SettingsView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">False</PublishTrimmed>
    <ApplicationIcon>Assets\PixHideIcon.ico</ApplicationIcon>
    <StartupObject>PixHide.WinUI3App.Program</StartupObject>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <PackageCertificateThumbprint>A994797ABEA87D02B648613BD7DDD95C15AA5FCE</PackageCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION </DefineConstants>
  </PropertyGroup>
</Project>